services:
  dagster-executor:
    build:
      context: .
      dockerfile: ./dagster/executor.Dockerfile
    container_name: dagster-executor
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DAGSTER_CURRENT_IMAGE: "dagster-executor"
    ports:
      - "4000:4000"
    depends_on:
      - db
    entrypoint: "dagster api grpc -h 0.0.0.0 -p 4000 -d /opt/dagster/app -m pipelines"
    volumes:
      # User Code
      - ./pipelines:/opt/dagster/app/pipelines
      # Run Storage
      - ./volumes/dagster:/opt/dagster/dagster_home
      # Persistent Storage
      - ./volumes/dagster/data:/opt/dagster/app/data

  dagster-dagit:
    build:
      context: .
      dockerfile: ./dagster/dagster.Dockerfile
    container_name: dagster-dagit
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3003:3003"
    volumes:
      # Docker client
      - /var/run/docker.sock:/var/run/docker.sock
      # Run Storage
      - ./volumes/dagster:/opt/dagster/dagster_home
      # Config
      - ./dagster/workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - ./dagster/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
    depends_on:
      # - db
      - dagster-executor
    entrypoint: "dagit -h 0.0.0.0 -p 3003 -w ./workspace.yaml"

  dagster-daemon:
    build:
      context: .
      dockerfile: ./dagster/dagster.Dockerfile
    container_name: dagster-daemon
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      # Docker Client
      - /var/run/docker.sock:/var/run/docker.sock
      # Run Storage
      - ./volumes/dagster:/opt/dagster/dagster_home
      # Config
      - ./dagster/workspace.yaml:/opt/dagster/dagster_home/workspace.yaml
      - ./dagster/dagster.yaml:/opt/dagster/dagster_home/dagster.yaml
    depends_on:
      # - db
      - dagster-executor
    entrypoint: dagster-daemon run
